### ISSUE TITLE
[Doc]: Fix Read The Doc Build "stable" build failing

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat#527]
### Describe your documentation update

Build: https://readthedocs.org/projects/xcdat/builds/21548322/

Traceback:
```bash
Running Sphinx v5.3.0
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
making output directory... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/site-packages/sphinx/registry.py", line 459, in load_extension
    mod = import_module(extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/site-packages/sphinx_book_theme/__init__.py", line 12, in <module>
    from pydata_sphinx_theme import _get_theme_options
ImportError: cannot import name '_get_theme_options' from 'pydata_sphinx_theme' (/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/site-packages/pydata_sphinx_theme/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/site-packages/sphinx/application.py", line 262, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/site-packages/sphinx/application.py", line 334, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 248, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 299, in init_templates
    self.theme = theme_factory.create(themename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/site-packages/sphinx/theming.py", line 232, in create
    self.load_extra_theme(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/site-packages/sphinx/theming.py", line 177, in load_extra_theme
    self.load_external_theme(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/site-packages/sphinx/theming.py", line 202, in load_external_theme
    self.app.registry.load_extension(self.app, entry_point.module)
  File "/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/site-packages/sphinx/registry.py", line 462, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinx_book_theme (exception: cannot import name '_get_theme_options' from 'pydata_sphinx_theme' (/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/site-packages/pydata_sphinx_theme/__init__.py))

Extension error:
Could not import extension sphinx_book_theme (exception: cannot import name '_get_theme_options' from 'pydata_sphinx_theme' (/home/docs/checkouts/readthedocs.org/user_builds/xcdat/conda/stable/lib/python3.10/site-packages/pydata_sphinx_theme/__init__.py))
```

**Comment by tomvothecoder** [comment]
This should work fine with the release of v0.6.0, which will be the latest stable version which will use the latest version of dependencies.

https://github.com/executablebooks/sphinx-book-theme/issues/711#issuecomment-1490561264:
> It looks like pydata-sphinx-theme 0.13.3 has a new public method, `pydata_sphinx_theme.utils.sphinx_book_theme_dict`. The fix I think would be to pin `pydata-sphinx-theme>=0.13.3` and use that new public API.
